// Client
export { SalesPlannerClient, ApiError } from './clients/index.js';
export type { ClientConfig } from './clients/index.js';

// Re-export all types from @sales-planner/shared for convenience
export type {
  // Entities
  User,
  Tenant,
  Shop,
  Sku,
  Brand,
  Category,
  Group,
  Status,
  Supplier,
  Warehouse,
  SalesHistory,
  Role,
  UserRole,
  ApiKey,
  Marketplace,
  Leftover,
  SeasonalCoefficient,
  SkuCompetitorMapping,
  CompetitorProduct,
  CompetitorSale,
  // Computed entities
  SkuMetrics,
  // DTOs — system
  CreateUserDto,
  CreateUserRequest,
  UpdateUserRequest,
  CreateTenantDto,
  CreateTenantRequest,
  UpdateTenantRequest,
  CreateTenantWithShopDto,
  CreateShopDto,
  CreateShopRequest,
  UpdateShopRequest,
  CreateApiKeyDto,
  CreateApiKeyRequest,
  CreateUserRoleDto,
  // DTOs — shop-scoped
  CreateSkuDto,
  CreateSkuRequest,
  UpdateSkuDto,
  UpdateSkuRequest,
  ImportSkuItem,
  CreateSalesHistoryDto,
  CreateSalesHistoryRequest,
  UpdateSalesHistoryDto,
  ImportSalesHistoryItem,
  CreateLeftoverDto,
  CreateLeftoverRequest,
  UpdateLeftoverDto,
  ImportLeftoverItem,
  CreateSeasonalCoefficientDto,
  CreateSeasonalCoefficientRequest,
  UpdateSeasonalCoefficientDto,
  ImportSeasonalCoefficientItem,
  CreateSkuCompetitorMappingDto,
  CreateSkuCompetitorMappingRequest,
  UpdateSkuCompetitorMappingDto,
  ImportSkuCompetitorMappingItem,
  CreateCompetitorProductDto,
  CreateCompetitorProductRequest,
  UpdateCompetitorProductDto,
  ImportCompetitorProductItem,
  CreateCompetitorSaleDto,
  CreateCompetitorSaleRequest,
  UpdateCompetitorSaleDto,
  ImportCompetitorSaleItem,
  ImportBrandItem,
  ImportCategoryItem,
  ImportGroupItem,
  ImportStatusItem,
  ImportSupplierItem,
  ImportWarehouseItem,
  ImportMarketplaceItem,
  CreateMarketplaceDto,
  CreateMarketplaceRequest,
  // Query types
  ShopContextParams,
  PaginationQuery,
  PeriodQuery,
  SalesHistoryQuery,
  LeftoverQuery,
  CompetitorSaleQuery,
  GetUserRolesQuery,
  // Response types
  PaginatedResponse,
  UserWithRolesAndTenants,
  UserRoleResponse,
  TenantInfo,
  ShopInfo,
  TenantWithShopAndApiKey,
  ImportResult,
  SkuImportResult,
  SalesHistoryImportResult,
  DeleteDataResult,
  // Export items
  SkuExportItem,
  SkuMetricsExportItem,
  BrandExportItem,
  CategoryExportItem,
  GroupExportItem,
  StatusExportItem,
  SupplierExportItem,
  WarehouseExportItem,
  MarketplaceExportItem,
  SalesHistoryExportItem,
  LeftoverExportItem,
  SeasonalCoefficientExportItem,
  SkuCompetitorMappingExportItem,
  CompetitorProductExportItem,
  CompetitorSaleExportItem,
  // Metadata types
  EntityFieldMetadata,
  EntityMetadata,
  EntitiesMetadata,
  FieldType,
} from '@sales-planner/shared';
