// Client
export { SalesPlannerClient, ApiError } from './clients/index.js';
export type { ClientConfig } from './clients/index.js';

// Re-export all types from @sales-planner/shared for convenience
export type {
  // Entities
  User,
  Tenant,
  Shop,
  Sku,
  SalesHistory,
  Role,
  UserRole,
  ApiKey,
  Marketplace,
  Leftover,
  SeasonalCoefficient,
  SkuCompetitorMapping,
  CompetitorProduct,
  CompetitorSale,
  // DTOs
  CreateUserDto,
  CreateTenantDto,
  CreateTenantWithShopDto,
  CreateShopDto,
  CreateSkuDto,
  CreateSkuRequest,
  UpdateSkuDto,
  UpdateSkuRequest,
  ImportSkuItem,
  CreateSalesHistoryDto,
  CreateSalesHistoryRequest,
  UpdateSalesHistoryDto,
  ImportSalesHistoryItem,
  CreateLeftoverDto,
  CreateLeftoverRequest,
  UpdateLeftoverDto,
  ImportLeftoverItem,
  CreateSeasonalCoefficientDto,
  CreateSeasonalCoefficientRequest,
  UpdateSeasonalCoefficientDto,
  ImportSeasonalCoefficientItem,
  CreateSkuCompetitorMappingDto,
  CreateSkuCompetitorMappingRequest,
  UpdateSkuCompetitorMappingDto,
  ImportSkuCompetitorMappingItem,
  CreateCompetitorProductDto,
  CreateCompetitorProductRequest,
  UpdateCompetitorProductDto,
  ImportCompetitorProductItem,
  CreateCompetitorSaleDto,
  CreateCompetitorSaleRequest,
  UpdateCompetitorSaleDto,
  ImportCompetitorSaleItem,
  CreateApiKeyDto,
  CreateRoleDto,
  CreateUserRoleDto,
  CreateMarketplaceDto,
  CreateMarketplaceRequest,
  // Query types
  ShopContextParams,
  PeriodQuery,
  LeftoverQuery,
  CompetitorSaleQuery,
  // Response types
  UserWithRolesAndTenants,
  TenantWithShopAndApiKey,
  ImportResult,
  DeleteDataResult,
  SkuExportItem,
  SalesHistoryExportItem,
  LeftoverExportItem,
  SeasonalCoefficientExportItem,
  SkuCompetitorMappingExportItem,
  CompetitorProductExportItem,
  CompetitorSaleExportItem,
  // Metadata types
  EntityFieldMetadata,
  EntityMetadata,
  EntitiesMetadata,
  FieldType,
} from '@sales-planner/shared';
