/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ApiKeys {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: Generated<number>;
  key: string;
  last_used_at: Timestamp | null;
  name: string | null;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface Marketplaces {
  created_at: Generated<Timestamp>;
  id: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Roles {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface SalesHistory {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  marketplace_id: string;
  period: Timestamp;
  quantity: Generated<number>;
  shop_id: number;
  sku_id: number;
  tenant_id: number;
  updated_at: Generated<Timestamp>;
}

export interface Shops {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  tenant_id: number;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Skus {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  shop_id: number;
  tenant_id: number;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  created_by: number;
  id: Generated<number>;
  owner_id: number | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface UserRoles {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  role_id: number;
  shop_id: number | null;
  tenant_id: number | null;
  user_id: number;
}

export interface Users {
  created_at: Generated<Timestamp>;
  default_shop_id: number | null;
  email: string;
  id: Generated<number>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface UserShops {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  shop_id: number;
  user_id: number;
}

export interface DB {
  api_keys: ApiKeys;
  marketplaces: Marketplaces;
  roles: Roles;
  sales_history: SalesHistory;
  shops: Shops;
  skus: Skus;
  tenants: Tenants;
  user_roles: UserRoles;
  user_shops: UserShops;
  users: Users;
}
