/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ApiKeys {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: Generated<number>;
  key: string;
  last_used_at: Timestamp | null;
  name: string | null;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface Brands {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  shop_id: number;
  tenant_id: number;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Categories {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  shop_id: number;
  tenant_id: number;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface CompetitorProducts {
  brand: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  marketplace_id: number;
  marketplace_product_id: Int8;
  shop_id: number;
  tenant_id: number;
  title: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CompetitorSales {
  competitor_product_id: number;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  period: Timestamp;
  quantity: Generated<number>;
  shop_id: number;
  tenant_id: number;
  updated_at: Generated<Timestamp>;
}

export interface Groups {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  shop_id: number;
  tenant_id: number;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Leftovers {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  period: Timestamp;
  quantity: Generated<number>;
  shop_id: number;
  sku_id: number;
  tenant_id: number;
  updated_at: Generated<Timestamp>;
  warehouse_id: number;
}

export interface Marketplaces {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  shop_id: number;
  tenant_id: number;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Migrations {
  applied_at: Generated<Timestamp | null>;
  name: string;
}

export interface NeonAuthAccount {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface NeonAuthInvitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: Generated<string>;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface NeonAuthJwks {
  createdAt: Timestamp;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  privateKey: string;
  publicKey: string;
}

export interface NeonAuthMember {
  createdAt: Timestamp;
  id: Generated<string>;
  organizationId: string;
  role: string;
  userId: string;
}

export interface NeonAuthOrganization {
  createdAt: Timestamp;
  id: Generated<string>;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface NeonAuthProjectConfig {
  allow_localhost: boolean;
  created_at: Generated<Timestamp>;
  email_and_password: Json | null;
  email_provider: Json | null;
  endpoint_id: string;
  id: Generated<string>;
  name: string;
  social_providers: Json;
  trusted_origins: Json;
  updated_at: Generated<Timestamp>;
}

export interface NeonAuthSession {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface NeonAuthUser {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: Generated<string>;
  image: string | null;
  name: string;
  role: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface NeonAuthVerification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface Roles {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface SalesHistory {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  marketplace_id: number;
  period: Timestamp;
  quantity: Generated<number>;
  shop_id: number;
  sku_id: number;
  tenant_id: number;
  updated_at: Generated<Timestamp>;
}

export interface SeasonalCoefficients {
  coefficient: Generated<number>;
  created_at: Generated<Timestamp>;
  group_id: number;
  id: Generated<number>;
  month: number;
  shop_id: number;
  tenant_id: number;
  updated_at: Generated<Timestamp>;
}

export interface Shops {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  tenant_id: number;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface SkuCompetitorMappings {
  competitor_product_id: number;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  shop_id: number;
  sku_id: number;
  tenant_id: number;
  updated_at: Generated<Timestamp>;
}

export interface Skus {
  brand_id: number | null;
  category_id: number | null;
  code: string;
  created_at: Generated<Timestamp>;
  group_id: number | null;
  id: Generated<number>;
  shop_id: number;
  status_id: number | null;
  supplier_id: number | null;
  tenant_id: number;
  title: string;
  title2: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Statuses {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  shop_id: number;
  tenant_id: number;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Suppliers {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  shop_id: number;
  tenant_id: number;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  created_by: number;
  id: Generated<number>;
  owner_id: number | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface UserRoles {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  role_id: number;
  shop_id: number | null;
  tenant_id: number | null;
  user_id: number;
}

export interface Users {
  created_at: Generated<Timestamp>;
  default_shop_id: number | null;
  email: string;
  id: Generated<number>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface UserShops {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  shop_id: number;
  user_id: number;
}

export interface Warehouses {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  shop_id: number;
  tenant_id: number;
  title: string;
  updated_at: Generated<Timestamp>;
}

// ============================================================================
// Materialized Views (manually maintained, not generated by kysely-codegen)
// ============================================================================

export interface MvSkuMetrics {
  id: number;
  sku_id: number;
  shop_id: number;
  tenant_id: number;
  sku_code: string;
  sku_title: string;
  // IDs for API responses
  group_id: number | null;
  category_id: number | null;
  brand_id: number | null;
  status_id: number | null;
  supplier_id: number | null;
  // Codes for export
  group_code: string | null;
  category_code: string | null;
  brand_code: string | null;
  status_code: string | null;
  supplier_code: string | null;
  last_period: string;
  last_period_sales: number;
  current_stock: number;
  days_of_stock: number | null;
  abc_class: string;
  sales_rank: number;
  computed_at: Date;
}

export interface DB {
  api_keys: ApiKeys;
  brands: Brands;
  categories: Categories;
  competitor_products: CompetitorProducts;
  competitor_sales: CompetitorSales;
  groups: Groups;
  leftovers: Leftovers;
  marketplaces: Marketplaces;
  migrations: Migrations;
  mv_sku_metrics: MvSkuMetrics;
  'neon_auth.account': NeonAuthAccount;
  'neon_auth.invitation': NeonAuthInvitation;
  'neon_auth.jwks': NeonAuthJwks;
  'neon_auth.member': NeonAuthMember;
  'neon_auth.organization': NeonAuthOrganization;
  'neon_auth.project_config': NeonAuthProjectConfig;
  'neon_auth.session': NeonAuthSession;
  'neon_auth.user': NeonAuthUser;
  'neon_auth.verification': NeonAuthVerification;
  roles: Roles;
  sales_history: SalesHistory;
  seasonal_coefficients: SeasonalCoefficients;
  shops: Shops;
  sku_competitor_mappings: SkuCompetitorMappings;
  skus: Skus;
  statuses: Statuses;
  suppliers: Suppliers;
  tenants: Tenants;
  user_roles: UserRoles;
  user_shops: UserShops;
  users: Users;
  warehouses: Warehouses;
}
