/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 *
 * Note: Field names are camelCase to match Kysely's CamelCasePlugin.
 * The plugin automatically maps camelCase ↔ snake_case when talking to the database.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ApiKeys {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  id: Generated<number>;
  key: string;
  lastUsedAt: Timestamp | null;
  name: string | null;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Brands {
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  shopId: number;
  tenantId: number;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Categories {
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  shopId: number;
  tenantId: number;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface CompetitorProducts {
  brand: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  marketplaceId: number;
  marketplaceProductId: Int8;
  shopId: number;
  tenantId: number;
  title: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface CompetitorSales {
  competitorProductId: number;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  period: Timestamp;
  quantity: Generated<number>;
  shopId: number;
  tenantId: number;
  updatedAt: Generated<Timestamp>;
}

export interface Groups {
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  shopId: number;
  tenantId: number;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Leftovers {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  period: Timestamp;
  quantity: Generated<number>;
  shopId: number;
  skuId: number;
  tenantId: number;
  updatedAt: Generated<Timestamp>;
  warehouseId: number;
}

export interface Marketplaces {
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  shopId: number;
  tenantId: number;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Migrations {
  appliedAt: Generated<Timestamp | null>;
  name: string;
}

export interface NeonAuthAccount {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface NeonAuthInvitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: Generated<string>;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface NeonAuthJwks {
  createdAt: Timestamp;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  privateKey: string;
  publicKey: string;
}

export interface NeonAuthMember {
  createdAt: Timestamp;
  id: Generated<string>;
  organizationId: string;
  role: string;
  userId: string;
}

export interface NeonAuthOrganization {
  createdAt: Timestamp;
  id: Generated<string>;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface NeonAuthProjectConfig {
  allowLocalhost: boolean;
  createdAt: Generated<Timestamp>;
  emailAndPassword: Json | null;
  emailProvider: Json | null;
  endpointId: string;
  id: Generated<string>;
  name: string;
  socialProviders: Json;
  trustedOrigins: Json;
  updatedAt: Generated<Timestamp>;
}

export interface NeonAuthSession {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface NeonAuthUser {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: Generated<string>;
  image: string | null;
  name: string;
  role: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface NeonAuthVerification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface Roles {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface SalesHistory {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  marketplaceId: number;
  period: Timestamp;
  quantity: Generated<number>;
  shopId: number;
  skuId: number;
  tenantId: number;
  updatedAt: Generated<Timestamp>;
}

export interface SeasonalCoefficients {
  coefficient: Generated<number>;
  createdAt: Generated<Timestamp>;
  groupId: number;
  id: Generated<number>;
  month: number;
  shopId: number;
  tenantId: number;
  updatedAt: Generated<Timestamp>;
}

export interface Shops {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  tenantId: number;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface SkuCompetitorMappings {
  competitorProductId: number;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  shopId: number;
  skuId: number;
  tenantId: number;
  updatedAt: Generated<Timestamp>;
}

export interface Skus {
  categoryId: number | null;
  code: string;
  createdAt: Generated<Timestamp>;
  groupId: number | null;
  id: Generated<number>;
  shopId: number;
  statusId: number | null;
  supplierId: number | null;
  tenantId: number;
  title: string;
  title2: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Statuses {
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  shopId: number;
  tenantId: number;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Suppliers {
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  shopId: number;
  tenantId: number;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Tenants {
  createdAt: Generated<Timestamp>;
  createdBy: number;
  id: Generated<number>;
  ownerId: number | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface UserRoles {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  roleId: number;
  shopId: number | null;
  tenantId: number | null;
  userId: number;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  defaultShopId: number | null;
  email: string;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface UserShops {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  shopId: number;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Warehouses {
  code: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  shopId: number;
  tenantId: number;
  title: string;
  updatedAt: Generated<Timestamp>;
}

// ============================================================================
// Materialized Views (manually maintained, not generated by kysely-codegen)
// ============================================================================

export interface MvSkuMetrics {
  id: number;
  skuId: number;
  shopId: number;
  tenantId: number;
  skuCode: string;
  skuTitle: string;
  // IDs for API responses
  groupId: number | null;
  categoryId: number | null;
  statusId: number | null;
  supplierId: number | null;
  // Codes for export
  groupCode: string | null;
  categoryCode: string | null;
  statusCode: string | null;
  supplierCode: string | null;
  lastPeriod: string;
  lastPeriodSales: number;
  currentStock: number;
  daysOfStock: number | null;
  abcClass: string;
  salesRank: number;
  computedAt: Date;
}

export interface DB {
  api_keys: ApiKeys;
  brands: Brands;
  categories: Categories;
  competitor_products: CompetitorProducts;
  competitor_sales: CompetitorSales;
  groups: Groups;
  leftovers: Leftovers;
  marketplaces: Marketplaces;
  migrations: Migrations;
  mv_sku_metrics: MvSkuMetrics;
  'neon_auth.account': NeonAuthAccount;
  'neon_auth.invitation': NeonAuthInvitation;
  'neon_auth.jwks': NeonAuthJwks;
  'neon_auth.member': NeonAuthMember;
  'neon_auth.organization': NeonAuthOrganization;
  'neon_auth.project_config': NeonAuthProjectConfig;
  'neon_auth.session': NeonAuthSession;
  'neon_auth.user': NeonAuthUser;
  'neon_auth.verification': NeonAuthVerification;
  roles: Roles;
  sales_history: SalesHistory;
  seasonal_coefficients: SeasonalCoefficients;
  shops: Shops;
  sku_competitor_mappings: SkuCompetitorMappings;
  skus: Skus;
  statuses: Statuses;
  suppliers: Suppliers;
  tenants: Tenants;
  user_roles: UserRoles;
  user_shops: UserShops;
  users: Users;
  warehouses: Warehouses;
}
